# Generated by Django 3.2.25 on 2024-07-07 04:03

from django.conf import settings  # type: ignore
from django.db import migrations, models  # type: ignore
import django.db.models.deletion  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(to="core.Tag"),
        ),
    ]
